// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (c) 2020 Association Prologin <association@prologin.org>

// This file contains the code to call the API functions from the C++ language.
// This file was generated by stechec2-generator. DO NOT EDIT.

#include "api.hh"

// This file only contains simple C++ wrappers around the API, that are
// basically already C++ functions, but with an `extern "C"`.

extern "C" erreur api_deplacer(direction dir);
erreur deplacer(direction dir)
{
    return api_deplacer(dir);
}

extern "C" erreur api_poser(position position_debut, direction dir, int pont_debut, int pont_fin);
erreur poser(position position_debut, direction dir, int pont_debut, int pont_fin)
{
    return api_poser(position_debut, dir, pont_debut, pont_fin);
}

extern "C" erreur api_debug_afficher_drapeau(position pos, debug_drapeau drapeau);
erreur debug_afficher_drapeau(position pos, debug_drapeau drapeau)
{
    return api_debug_afficher_drapeau(pos, drapeau);
}

extern "C" case_type api_type_case(position pos);
case_type type_case(position pos)
{
    return api_type_case(pos);
}

extern "C" int api_panda_sur_case(position pos);
int panda_sur_case(position pos)
{
    return api_panda_sur_case(pos);
}

extern "C" int api_bebe_panda_sur_case(position pos);
int bebe_panda_sur_case(position pos)
{
    return api_bebe_panda_sur_case(pos);
}

extern "C" position api_position_panda(int id_joueur, int id_panda);
position position_panda(int id_joueur, int id_panda)
{
    return api_position_panda(id_joueur, id_panda);
}

extern "C" pont_type api_info_pont(position pos);
pont_type info_pont(position pos)
{
    return api_info_pont(pos);
}

extern "C" panda_info api_info_panda(position pos);
panda_info info_panda(position pos)
{
    return api_info_panda(pos);
}

extern "C" std::vector<panda_info> api_liste_pandas();
std::vector<panda_info> liste_pandas()
{
    return api_liste_pandas();
}

extern "C" std::vector<bebe_info> api_liste_bebes();
std::vector<bebe_info> liste_bebes()
{
    return api_liste_bebes();
}

extern "C" std::vector<position> api_positions_adjacentes(position pos);
std::vector<position> positions_adjacentes(position pos)
{
    return api_positions_adjacentes(pos);
}

extern "C" position api_position_dans_direction(position pos, direction dir);
position position_dans_direction(position pos, direction dir)
{
    return api_position_dans_direction(pos, dir);
}

extern "C" int api_direction_entre_positions(position origine, position cible);
int direction_entre_positions(position origine, position cible)
{
    return api_direction_entre_positions(origine, cible);
}

extern "C" std::vector<action_hist> api_historique();
std::vector<action_hist> historique()
{
    return api_historique();
}

extern "C" int api_score(int id_joueur);
int score(int id_joueur)
{
    return api_score(id_joueur);
}

extern "C" int api_moi();
int moi()
{
    return api_moi();
}

extern "C" int api_adversaire();
int adversaire()
{
    return api_adversaire();
}

extern "C" tour_info api_info_tour();
tour_info info_tour()
{
    return api_info_tour();
}

extern "C" carte_info api_info_carte();
carte_info info_carte()
{
    return api_info_carte();
}

extern "C" void api_afficher_case_type(case_type v);
void afficher_case_type(case_type v)
{
    api_afficher_case_type(v);
}

extern "C" void api_afficher_direction(direction v);
void afficher_direction(direction v)
{
    api_afficher_direction(v);
}

extern "C" void api_afficher_erreur(erreur v);
void afficher_erreur(erreur v)
{
    api_afficher_erreur(v);
}

extern "C" void api_afficher_action_type(action_type v);
void afficher_action_type(action_type v)
{
    api_afficher_action_type(v);
}

extern "C" void api_afficher_debug_drapeau(debug_drapeau v);
void afficher_debug_drapeau(debug_drapeau v)
{
    api_afficher_debug_drapeau(v);
}

extern "C" void api_afficher_position(position v);
void afficher_position(position v)
{
    api_afficher_position(v);
}

extern "C" void api_afficher_pont_type(pont_type v);
void afficher_pont_type(pont_type v)
{
    api_afficher_pont_type(v);
}

extern "C" void api_afficher_panda_info(panda_info v);
void afficher_panda_info(panda_info v)
{
    api_afficher_panda_info(v);
}

extern "C" void api_afficher_bebe_info(bebe_info v);
void afficher_bebe_info(bebe_info v)
{
    api_afficher_bebe_info(v);
}

extern "C" void api_afficher_tour_info(tour_info v);
void afficher_tour_info(tour_info v)
{
    api_afficher_tour_info(v);
}

extern "C" void api_afficher_carte_info(carte_info v);
void afficher_carte_info(carte_info v)
{
    api_afficher_carte_info(v);
}

extern "C" void api_afficher_action_hist(action_hist v);
void afficher_action_hist(action_hist v)
{
    api_afficher_action_hist(v);
}
